name: Code Coverage 

on: [push]

env:
  BUILD_TYPE: Debug 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get -yq update
          sudo apt-get install -yq cmake
          gcc --version

      - name: Configure
        shell: bash
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        shell: bash
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run Test
        shell: bash
        run: |
          pip3 install gcovr
          pip3 install -r tools/mock_server/requirements.txt
          nohup python3 tools/mock_server/server.py &
          sleep 1
          cd build
          ctest -V

      - name: Generage Code Coverage Report
        shell: bash
        run: cmake --build ${{github.workspace}}/build --target ctest_coverage

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ${{github.workspace}}/build/ctest_coverage.xml
          fail_ci_if_error: true
          functionalities: fix