name: MacOS

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install ninja
          clang++ --version

      - name: Configure
        shell: bash
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -G "Ninja"

      - name: Build
        shell: bash
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test 
        shell: bash
        run: |
          pip3 install -r tools/mock_server/requirements.txt
          nohup python3 tools/mock_server/server.py &
          sleep 1
          cd build
          ctest -V